version: '3'
services:
  web:
    build: .
    ports:
      - "4001:4000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Vermilion9$"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
  
